### ISSUE TITLE
Use with tailwind / other frameworks

### ISSUE THREAD

**Issue by davestewart** [visualjerk/vue-cion-design-system#19]
This looks cool.

Maybe I misunderstand how this works, but can you use this with existing frameworks?

For example, an existing CSS setup with Tailwind, and Element UI for components?

I presume that with this you need to use its styles and components?

If not, is Storybook a better bet?

**Comment by visualjerk** [comment]
Sorry for the late answer.

Don't mistake this repository for a component documentation. It is a design system boilerplate with some styles, a component library and an integrated component documentation.

If you are looking to document your own components, Storybook is a good choice.
