### ISSUE TITLE
Copy field does not work on mobile. 

### ISSUE THREAD

**Issue by appinteractive** [visualjerk/vue-cion-design-system#2]
Page scrolls to the bottom when clicking the copy field. Value is not copied.

**Comment by visualjerk** [comment]
Thanks! This bug is fixed in the current version.

**Comment by appinteractive** [comment]
Is it already deployed on the demo site?

**Comment by visualjerk** [comment]
The last fix only worked partially on iOS. The new version seems to work reliable.
