### ISSUE TITLE
Page examples are not visible

### ISSUE THREAD

**Issue by appinteractive** [visualjerk/vue-cion-design-system#6]
For some reason the [page examples ](https://styleguide.cion.visualjerk.de/layout/dspage) are not visible anymore!

<img width="847" alt="grafik" src="https://user-images.githubusercontent.com/432828/47710112-375b3580-dc32-11e8-977a-4f39faa112d1.png">

**Comment by visualjerk** [comment]
Fixed this issue in master branch
