### ISSUE TITLE
Switch to Dark Mode?

### ISSUE THREAD

**Issue by appinteractive** [visualjerk/vue-cion-design-system#8]
@visualjerk Is there a way that the components could easily switch to dark mode without the need to dublicate the whole styleguide?

**Comment by visualjerk** [comment]
The only "simple" option that pops to my mind right now would be to do this depending on an environment variable.

Depending on its value we could then either prepend tokens.scss or tokens-dark.scss to shared.scss via [webpacks sass-loader](https://webpack.js.org/loaders/sass-loader/#environment-variables).

**Comment by appinteractive** [comment]
But that would not happen on production I think!?

**Comment by visualjerk** [comment]
Just for reference:
https://github.com/webpack-contrib/style-loader#useable
https://www.npmjs.com/package/vue-theme-loader

**Comment by visualjerk** [comment]
In current master you find the option to add themes by simply creating a subfolder in the tokens folder. While this is not documented yet, it is pretty self explaining. Happy theming 😄
