### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by appinteractive** [visualjerk/vue-cion-design-system#9]
Currently the way the styleguide is used prevents from getting the changes (or fixes) back to the main projects as the git link gets broken. At least thats the case for my current setup as I had to thorw await the git link. 

Is there a good way or best practice to keep the git link? An upstream remote does not work as the styleguide lives in a subdirectory. What are your thoughts on that @visualjerk ?

**Comment by visualjerk** [comment]
For now this repo is just a boilerplate for you to create your own design system. Therefor the only way of keeping up to date is by copying new components over to your own implementation.

That said I am thinking of a new architecture that would allow to use it as a component framework that is customizable to the core. However that would be out of scope of the project right now as it requires a completely new approach.
